apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-config
  labels:
    app: {{ template "name" . }}
    chart: {{ template "dashboard.chart" . }}
    release: {{ .Release.Name | replace "." "_" }}
    heritage: {{ .Release.Service }}
data:
  config.ru: |
    require 'sinatra/cyclist'
    require 'dashing'
    configure do
      set :auth_token, 'YOUR_AUTH_TOKEN'
      helpers do
        def protected!
          # Put any authentication code you want in here.
          # This method is run before accessing any resource.
        end
      end
    end
    map Sinatra::Application.assets_prefix do
      run Sinatra::Application.sprockets
    end
    set :routes_to_cycle_through, [
           :adp_dashboard,
           {{- range .Values.pages }} 
           :{{ . }}_dashboard,
           {{- end }}
    ]
    run Sinatra::Application
  jenkins_config.json: {{ .Values.jenkinsServers | quote}}
