apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-jobs
  labels:
    app: {{ template "name" . }}
    chart: {{ template "dashboard.chart" . }}
    release: {{ .Release.Name | replace "." "_" }}
    heritage: {{ .Release.Service }}
data:
{{ (.Files.Glob "jobs/*").AsConfig | indent 2 }}
