apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ template "dashboard.chart" . }}
    release: {{ .Release.Name | replace "." "_" }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - port: {{ .Values.service.externalPort }}
    name: http
    targetPort: {{ .Values.service.internalPort }}
    {{- if and (eq .Values.service.type "NodePort") (.Values.service.nodePort) }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}
